version: "3.9"
services:
  api:
    build:
      context: ..
      dockerfile: infra/Dockerfile.api
    env_file:
      - ../backend/.env
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
  worker:
    build:
      context: ..
      dockerfile: infra/Dockerfile.worker
    env_file:
      - ../backend/.env
    command: celery -A backend.app.workers.celery_app worker -Q default,rss_ingestion --loglevel=info
    depends_on:
      - db
      - redis
  beat:
    build:
      context: ..
      dockerfile: infra/Dockerfile.worker
    env_file:
      - ../backend/.env
    command: celery -A backend.app.workers.celery_app beat --loglevel=info
    depends_on:
      - db
      - redis
  frontend:
    build:
      context: ..
      dockerfile: infra/Dockerfile.frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - api
  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: insighthub
    ports:
      - "5432:5432"
  redis:
    image: redis:7
    ports:
      - "6379:6379"
